#' @importFrom SummarizedExperiment colData
#' @importFrom SummarizedExperiment assayNames
#' @importFrom SummarizedExperiment assays
#' @importFrom SummarizedExperiment assay
#' @importFrom SpatialExperiment SpatialExperiment
#' @importFrom S4Vectors metadata
#' @importFrom Matrix colSums
#' @importFrom Matrix t
#' @importFrom Matrix rowSums
#' @importFrom methods is
#' @importFrom BiocGenerics unique
#' @importFrom BiocGenerics colnames
#' @importFrom BiocGenerics rownames
#' @importFrom BiocGenerics lapply
#' @importFrom BiocGenerics do.call
#' @importFrom BiocGenerics match
#' @importFrom BiocGenerics mapply
#' @importFrom BiocGenerics counts
#' @importFrom BiocGenerics get
#' @importFrom data.table setorder
#' @importFrom data.table as.data.table
#' @importFrom edgeR DGEList
#' @importFrom edgeR calcNormFactors
#' @importFrom edgeR estimateDisp
#' @importFrom edgeR glmFit
#' @importFrom edgeR glmLRT
#' @importFrom edgeR topTags
#' @importFrom limma is.fullrank
#' @importFrom stats model.matrix
#' @importFrom dplyr arrange
#' @importFrom dplyr '%>%'
#' @importFrom dplyr bind_rows
#' @importFrom dplyr filter
#' @importFrom BiocGenerics eval
#' @importFrom BiocGenerics append
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_void
#' @importFrom ggplot2 geom_polygon
#' @importFrom ggplot2 coord_equal
#' @importFrom ggplot2 scale_fill_gradient2
#' @importFrom ggplot2 scale_alpha
#' @importFrom ggplot2 scale_fill_discrete
#' @importFrom ggplot2 scale_color_discrete
#' @importFrom ggplot2 unit
#' @importFrom ggnewscale new_scale_fill
#' @importFrom ggnewscale new_scale_color
#' @importFrom patchwork wrap_plots 
#' @importFrom assertthat assert_that
#' @importFrom ggforce geom_mark_hull
#' @importFrom cowplot get_legend
#' @importFrom ggpubr as_ggplot
#' @importFrom BiocParallel bplapply
#' 
NULL