#' @importFrom SummarizedExperiment colData
#' @importFrom SummarizedExperiment colData<- 
#' @importFrom SummarizedExperiment assayNames
#' @importFrom SummarizedExperiment assays
#' @importFrom SummarizedExperiment assay
#' @importFrom SummarizedExperiment assay<-
#' @importFrom SpatialExperiment SpatialExperiment
#' @importFrom SpatialExperiment spatialCoords
#' @importFrom SpatialExperiment spatialCoords<-
#' @importFrom S4Vectors metadata
#' @importFrom Matrix colSums
#' @importFrom Matrix t
#' @importFrom Matrix rowSums
#' @importFrom methods is
#' @importFrom methods show
#' @importFrom BiocGenerics unique
#' @importFrom BiocGenerics colnames
#' @importFrom BiocGenerics rownames
#' @importFrom BiocGenerics lapply
#' @importFrom BiocGenerics do.call
#' @importFrom BiocGenerics match
#' @importFrom BiocGenerics mapply
#' @importFrom BiocGenerics counts
#' @importFrom BiocGenerics get
#' @importFrom data.table setorder
#' @importFrom edgeR DGEList
#' @importFrom edgeR calcNormFactors
#' @importFrom edgeR estimateDisp
#' @importFrom edgeR glmFit
#' @importFrom edgeR glmLRT
#' @importFrom edgeR glmQLFit
#' @importFrom edgeR glmQLFTest
#' @importFrom edgeR topTags
#' @importFrom limma is.fullrank
#' @importFrom stats model.matrix
#' @importFrom stats density
#' @importFrom stats quantile
#' @importFrom stats relevel
#' @importFrom dplyr arrange
#' @importFrom dplyr '%>%'
#' @importFrom dplyr bind_rows
#' @importFrom dplyr filter
#' @importFrom BiocGenerics eval
#' @importFrom BiocGenerics append
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_void
#' @importFrom ggplot2 geom_polygon
#' @importFrom ggplot2 coord_equal
#' @importFrom ggplot2 scale_fill_gradient2
#' @importFrom ggplot2 scale_alpha
#' @importFrom ggplot2 scale_fill_discrete
#' @importFrom ggplot2 scale_color_discrete
#' @importFrom ggplot2 unit
#' @importFrom ggplot2 geom_sf
#' @importFrom ggnewscale new_scale_fill
#' @importFrom ggnewscale new_scale_color
#' @importFrom patchwork wrap_plots 
#' @importFrom patchwork plot_layout
#' @importFrom assertthat assert_that
#' @importFrom ggforce geom_mark_hull
#' @importFrom BiocParallel bplapply
#' @importFrom BiocParallel SerialParam
#' @importFrom sf st_as_sf 
#' @importFrom sf st_sf 
#' @importFrom sf st_union 
#' @importFrom sf st_cast 
#' @importFrom sf st_make_valid
#' @importFrom sf st_is_empty
#' @importFrom terra rast 
#' @importFrom terra as.polygons 
#' @importFrom terra set.ext
#' @importFrom spatstat.explore density.ppp 
#' @importFrom spatstat.explore bw.diggle
#' @importFrom spatstat.geom as.ppp 
#' @importFrom spatstat.geom marks<-
#' @importFrom spatstat.geom marks
#' @importFrom scuttle summarizeAssayByGroup
#' 
NULL